3 module tasks
js-tasks-ru/jsbasic-20210420_ir-klypina pull request #7
Opened 2021-05-04 10:59 UTC by OliviaTa

2021-05-04 10:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-05-04 19:13 UTC, SinimaWath requested changes

2021-05-04 19:13 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  }
давай тут заиспользуем map

2021-05-04 19:13 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return users.map(item => item.name);
Давай применим деструктуризацию в аргументах функции для практики ;)

2021-05-04 19:13 UTC, SinimaWath commented on 3-module/4-task/index.js
> +    .map(user => `${user.name}, ${user.balance}`)
Давай тут тоже попробуем деструкторизацию в аргументах функции

2021-05-05 09:56 UTC, OliviaTa commented on 3-module/3-task/index.js
> +  }
Хочу поинтересоваться, почему в этом примере map подходит больше? Ведь нам не нужно изменять первый элемент массива и в map нужно будет добавлять условие, проверяющее первый ли это элемет на каждом шаге цикла.

2021-05-06 14:18 UTC, SinimaWath approved these changes

2021-05-06 14:19 UTC, merged